

name: AMAR WORKFLOW

on:
  
  push:
    branches: [ "master" ]
  




jobs:
  
  # FIRST JOB IN UBUNTU
  my_first_job:
    name: Job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python ${GITHUB_WORKSPACE}/scripts/intro.py 5,5
    
   #SECOND JOB IN WINDOWS 
  my_second_job:
    name: Job2
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python ${GITHUB_WORKSPACE}/scripts/intro.py 5,5
    